---
  - name: Configuring vscodium...
    #User settings
    shell: rm -rf /home/showen/.config/VSCodium/User/
  - name: 
    unarchive:
      src: /home/showen/neon-build/roles/setup/applications/vscodium/files/vscodium.tar.xz
      dest: /home/showen/.config/VSCodium/

    #Extensions
  - name: Configuring vscodium extensions...
    shell: cat /home/showen/neon-build/roles/setup/applications/vscodium/files/extension.txt | xargs -L 1 codium --install-extension 
  - name:
    copy:
      src: /home/showen/neon-build/roles/setup/applications/vscodium/files/extensions.json
      dest: /home/showen/.vscode-oss/extensions/extensions.json
