---
  - name: Configuring vscodium...
    #User settings
    shell: rm -rf /home/showen/.config/VSCodium/User/
  - name: 
    unarchive:
      src: /home/showen/kubuntu-build/roles/setup/applications/vscodium/files/vscodium.tar.xz
      dest: /home/showen/.config/VSCodium/

    #Extensions
  - name: Configuring vscodium extensions...
    shell: cat /home/showen/kubuntu-build/roles/setup/applications/vscodium/files/extension.txt | xargs -L 1 codium --no-sandbox --user-data-dir /home/showen/ --install-extension
