---
  - name: Backing up vscodium...
    #User Settings
    shell: 'tar -C /home/showen/.config/VSCodium -cJvf /home/showen/neon-build/roles/setup/applications/vscodium/files/vscodium.tar.xz User/'
  - name: Backing up vscodium extensions...
    #Extensions
    shell: codium --list-extensions --no-sandbox --user-data-dir /home/showen/ > /home/showen/neon-build/roles/setup/applications/vscodium/files/extension.txt 
