---
  - name: Backing up 'kubuntu-build' to USB...
    shell: rm -rf /media/backup/usb/Kubuntu/kubuntu-build/*
  - name:
    copy:
      src: /home/showen/kubuntu-build/ 
      dest: /media/backup/usb/Kubuntu/kubuntu-build/

  - name: Backing up 'kubuntu-build' to GitHub...
    git_config:
      name: user.email
      value: "showen@proton.me"
      scope: global
  - name: 
    shell: "git add . && git commit -m '1.0' && git push"
    args:
      chdir: /home/showen/kubuntu-build/
